language: python
env:
  global:
  - secure: "pjSwHOyxzEAS1XTGPiNRd5NDWYCRfw/i7LXFKrqJmV+9son7crhoRpMFxxqhh2YyQy2Gwe7pM++6OEAeV3CdZIW8qgjDK73XEMCwU43M2NgkR9zn2MYQ8qX4aBhtKXUhAl+kFhl2mpzszx21C7+R8HKCnfN0wl6NNaPPcVn0F/VHFKChnlqvCHZKqmR8/GZoP+CyrY7ZoVFXwnyg2We/cTOKT7p4EdsBMYRsPP3L6sRQ4QNX6LF+zGmbttTwVxrRp6psl6HmM2u91AJzv1EL9JcBlU0P+Z54YYqwugE52IPk+wUv9/gu0SlmwxQ5n5EelJCkaHDvLj2WY9ZUwGkL+hmyV43EKYu31MYg6u/3CzelpOPUBp1ZYsYrNvWol1+/kXeJZGstaP4Fh+mNO4caXspmVMhuDsWrgfJMVQUwKPs/b/vYgvKx+sLGSGhghI/d9LpptQ0144FBoshUcOF6ZVPm1bk+Naj5MYxxo4eRguNjFwnibFlZNALj+rKwFCpTAzhIQI2STX3GP65gMlGO1KYuf3upJkEm+rUe+2fL5n/97m2WZ26FHybBgPcVEU9szL+1L6IJvENE5icWC4VDYe3hiYMAoWZT582xzJJlWO1IDP7aerYwMwww1rzzqpn9vag9bggIXw3N2ZgSa56jMNumE6NHXcu7P/BFCON4oy4="
  - secure: "jRDRf3LUjWfW+nVB81iXJ3RUIkrf/t/+7fe7P5/4NVSFzlLZtNRA7ZGZC3vAnrnY/dXjVOVr78fCkdLAFVIE46rlr10NQp+DL0zo09iHp4I6oVNDrRYuJ7zpeBzqkAyaeQn/Ud0Z9e/46S84vJp5e7avH7UENDix46qhAjL5qeLmfJuSiusZ3Uc9/JydrosStdov0jGOxbw4+ujpMk66w53Vq/yXhAllPsuN1Q3c9nhG9KCc3pV3PMToFgHP0L9C8+XKrHNNgFCypgQ3JwpBlS/dqP1JJSyGcw+pHs1BiTTx8ORH0mLsHqgdwFd4VtDlY4PwlxNerGJ47PON36QomwM3N72K/Z3MnA7oP+HP+nVvHQl8GU/15gfnfPymN8xe+WIsFoVkEMgade0Zdkh+GeWrDw2kQiNoN/TL+FJgR+oDXz5FD7Nt3w8bbGleuDdhdvVHtdDVGmL5Q+oigJr1BlZaP3AQ6b5In3Mn3kcQGKu8TC7QAe1wZhGiJfknWepbzZHLS4b4RUuqEUa+A+yB3byp3Gm30UWBnHrjADHSW0RQWP+T34qZUAp0O5gNYC5q+D9hb30BEh+Xxt34WectSTSHrpORX4ed62ld3Hs1ILF5wnLFuzpZkdZdS6I0AQeqG4NdIWzRre+L3pDP2RFG00qxjKB7SSu98OvIlgPqbDU="
  - BOB_UPLOAD_WHEEL=1
matrix:
  include:
  - python: 2.7
    env:
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
  - python: 3.4
  - python: 3.5
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes libboost-all-dev libblitz1-dev libmatio-dev libatlas-dev libatlas-base-dev liblapack-dev libsox-dev libhdf5-serial-dev texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
- pip install --upgrade pip
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel sphinx nose coverage cpp-coveralls pillow
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel --pre -r requirements.txt coveralls
install:
- python bootstrap-buildout.py
- CPPFLAGS=--coverage LDFLAGS=--coverage ./bin/buildout buildout:debug=false buildout:develop=. buildout:extensions=bob.buildout buildout:auto-checkout=
script:
- ./bin/python -c 'import pkg_resources; from bob.io.audio import get_config; print(get_config())'
- ./bin/coverage run --source=bob.io.audio ./bin/nosetests -sv
- ./bin/sphinx-build -b doctest doc sphinx
- ./bin/sphinx-build -b html doc sphinx
after_success:
- cpp-coveralls --build-root=`pwd` --exclude=src --exclude-pattern=".*Compiler.*" --dump=cpp_cov.json
- coveralls --merge=cpp_cov.json
- wget https://raw.githubusercontent.com/bioidiap/bob.extension/master/scripts/upload-{sphinx,wheel}.sh
- chmod a+x upload-sphinx.sh upload-wheel.sh
- ./upload-sphinx.sh
- ./upload-wheel.sh
